site_name: Cristiani LGBT+ Sicilia
site_description: Comunit√† di fede inclusiva e accogliente in Sicilia
site_url: https://cristianilgbtsicilia.it

theme:
  name: material
  custom_dir: overrides
  language: it
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Passa al tema scuro
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Passa al tema chiaro
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - content.tooltips
    - navigation.tabs
  favicon: assets/favicon.ico
  logo: assets/favicon.png

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/cristianilgbtsicilia
      name: Seguici su Facebook
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/cristianilgbtsicilia
      name: Seguici su Instagram
    - icon: fontawesome/solid/envelope
      link: mailto:info@cristianilgbtsicilia.org
      name: Contattaci via email

extra_css:
  - stylesheets/extra.css
  - https://fonts.googleapis.com/icon?family=Material+Icons

plugins:
  - search
  - blog:
      blog_dir: news